### ISSUE TITLE
fix: seems the PulsarGeoReplication object doesn't support the tls enabled PulsarConnection

### ISSUE THREAD

**Issue by ericsyh** [streamnative/pulsar-resources-operator#138]
### How to reproduce 

1. create two clusters on SN Cloud which uses the tls endpoints, and an example YAML below
```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: us-east
  namespace: snc
spec:
  adminServiceSecureURL: https://us-east-beee261c-b7a1-46f4-8e0f-95b64724d73a
  brokerServiceSecureURL: pulsar+ssl://us-east-beee261c-b7a1-46f4-8e0f-95b64724d73a
  clusterName: us-east
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: us-west
  namespace: snc
spec:
  adminServiceSecureURL: https://us-west-0c11aeb4-2da2-4ee4-b086-745835b33893
  brokerServiceSecureURL: pulsar+ssl://us-west-0c11aeb4-2da2-4ee4-b086-745835b33893
  clusterName: us-west
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarGeoReplication
metadata:
  name: east-to-west
  namespace: snc
spec:
  connectionRef:
    name: us-east
  destinationConnectionRef:
    name: us-west
  lifecyclePolicy: CleanUpAfterDeletion
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarGeoReplication
metadata:
  name: west-to-east
  namespace: snc
spec:
  connectionRef:
    name: us-west
  destinationConnectionRef:
    name: us-east
  lifecyclePolicy: CleanUpAfterDeletion
```
2. After applying the YAML, i will get error messages from the operator 

```
{"severity":"error","timestamp":"2023-08-15T14:10:43Z","logger":"controller.pulsarconnection","message":"Reconciler error","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","name":"us-east","namespace":"snc","error":"PulsarConnection.resource.streamnative.io \"us-east\" is invalid: spec.adminServiceURL: Invalid value: \"\": spec.adminServiceURL in body should match '^https?://.+$'","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
{"severity":"error","timestamp":"2023-08-15T14:10:44Z","logger":"controller.pulsarconnection","message":"Reconciler error","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","name":"us-west","namespace":"snc","error":"PulsarConnection.resource.streamnative.io \"us-west\" is invalid: spec.adminServiceURL: Invalid value: \"\": spec.adminServiceURL in body should match '^https?://.+$'","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
{"severity":"error","timestamp":"2023-08-15T14:11:04Z","logger":"controller.pulsarconnection","message":"Reconciler error","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","name":"us-east","namespace":"snc","error":"PulsarConnection.resource.streamnative.io \"us-east\" is invalid: spec.adminServiceURL: Invalid value: \"\": spec.adminServiceURL in body should match '^https?://.+$'","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
{"severity":"error","timestamp":"2023-08-15T14:11:04Z","logger":"controller.pulsarconnection","message":"Reconciler error","reconciler group":"resource.streamnative.io","reconciler kind":"PulsarConnection","name":"us-west","namespace":"snc","error":"PulsarConnection.resource.streamnative.io \"us-west\" is invalid: spec.adminServiceURL: Invalid value: \"\": spec.adminServiceURL in body should match '^https?://.+$'","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
```
3. If i remove the `PulsarGeoReplication` objects, the error will be gone.
