### ISSUE TITLE
PulsarSource does not publish in the correct tenant/namespace

### ISSUE THREAD

**Issue by brunocascio** [streamnative/pulsar-resources-operator#228]
Hello folks,

I'm using PulsarSource with RabbitMQ integration everything works ok, but I've noticed seems it's not publishing in the correct tenant/namespace. Instead it is publishing on `public/default/<topicName>`.

Here's my code:

```yaml
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarSource
metadata:
  name: rabbitmq-source
spec:
  className: org.apache.pulsar.io.rabbitmq.RabbitMQSource
  connectionRef:
    name: pulsar-connection
  archive:
    url: https://archive.apache.org/dist/pulsar/pulsar-3.3.0/connectors/pulsar-io-rabbitmq-3.3.0.nar
  configs:
    host: rabbitmq.example.com
    port: "5672"
    virtualHost: myvhost
    queueName: myqueue
    username: myuser
    connectionName: pulsar-connection
    password: mypass
    passive: 'true'
  lifecyclePolicy: CleanUpAfterDeletion
  name: rabbitmq-source
  tenant: mytenant
  namespace: myns
  topicName: mytopic
  parallelism: 1
  processingGuarantees: ATLEAST_ONCE
```
