### ISSUE TITLE
v0.9.0 modifies custom resource spec

### ISSUE THREAD

**Issue by piotr-bzdyl-vertexinc** [streamnative/pulsar-resources-operator#308]
After upgrading to v0.9.0 we have noticed that the operator modifies the spec of the custom resource, e.g. PulsarTopic. This causes endless competition between the operator and continuous deployment (e.g. [FluxCD](https://fluxcd.io/):
- continuous deployment process ensures the resource matches the code from git
- pulsar-resources-operator applies this change but modifies the spec part of the resource
- continuous deployment process detects drift in the resource spec, thus it applies it again to match the code from git
- pulsar-resources-operator detects the change in the resource and modifies the spec part again
- and so on...

I was able to reproduce it with the following `PulsarTopic` applied by continuous deployment:

```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: test-topic
spec:
  connectionRef:
    name: test-cluster
  name: persistent://test-tenant/test-ns/test-topic
  persistent: true
  retentionTime: 14d
  retentionSize: -1
```

The operator modifies it by adding `spec.partitions: 0`.
