### ISSUE TITLE
422 Invalid schema definition data for JSON schema

### ISSUE THREAD

**Issue by filipqlrf** [streamnative/pulsar-resources-operator#311]
I'm trying to deploy a topic with a JSON schema using the operator.
I tried to use my custom schema and I'm getting:
`422 Invalid schema definition data for JSON schema`

The same schema works when I upload it using pulsar-admin. 

Then I took the example from here:
https://github.com/streamnative/pulsar-resources-operator/blob/main/docs/pulsar_topic.md

and created a yaml definition like:

```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: my-topic
  namespace: pulsar
spec:
  connectionRef:
    name: pulsar-connection
  name: persistent://my-tenant/my-ns/my-topic
  partitions: 16
  persistent: true
  schemaInfo:
    schema: >-
      "{\"fields\":[{\"name\":\"ID\",\"type\":\"int\"},{\"name\":\"Name\",\"type\":\"string\"}],\"name\":\"Example\",\"namespace\":\"pulsar\",\"type\":\"record\"}"
    type: JSON
```

Which again throws the same issue. How to find more details about the error?
