### ISSUE TITLE
[feat](topic): Schema support on topic resource

### ISSUE THREAD

**Issue by ericsyh** [streamnative/pulsar-resources-operator#39]

**Comment by ericsyh** [comment]
#### Topic CRD with Schema exmaple: 

```
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: "test-pulsar-topic123"
  namespace: test
spec:
  name: persistent://test-tenant/testns/topic123
  connectionRef:
    name: "test-pulsar-connection"
  schemaInfo:
    type: "JSON"
    schema: "{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.foo\",\"fields\":[{\"name\":\"file1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"file2\",\"type\":\"string\",\"default\":null},{\"name\":\"file3\",\"type\":[\"null\",\"string\"],\"default\":\"dfdf\"}]}"
    properties: {}
```
```
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: "test-pulsar-topic123"
  namespace: test
spec:
  name: persistent://test-tenant/testns/topic123
  connectionRef:
    name: "test-pulsar-connection"
  schemaInfo:
    type: "STRING"
    schema: ""
    properties: "{"key1": "value1"}"
```

#### Schema Manage workflow

* Add schema on topic resources: Use [schemas upload API](https://pulsar.apache.org/docs/next/schema-manage#upload-a-schema) to add schema on the topic.
* Update schema on topic resources: Use [schemas upload API](https://pulsar.apache.org/docs/next/schema-manage#upload-a-schema) to update schema on the topic.
* Delete schema on topic resources: Use [schemas delete api](https://pulsar.apache.org/docs/next/schema-manage#delete-a-schema) to delete schema on the topic.
