### ISSUE TITLE
[feat](resource): support geo-replication configs

### ISSUE THREAD

**Issue by ericsyh** [streamnative/pulsar-resources-operator#40]

**Comment by ericsyh** [comment]
### Draft now

We can define a `PulsarGeoReplication` new CR to describe the replicate logic 

```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarGeoReplication
metadata:
  name: pulsar-geo-sample
  namespace: geo
spec:
  replicationList:
    - name: us-west
       sourceConnectionRef: 
  	  name: "us-west"
       destinationConnectionRef: 
  	  name: "us-east, us-cent"
    - name: us-east
       sourceConnectionRef: 
  	  name: "us-east"
       destinationConnectionRef: 
  	  name: "us-west, us-cent"
    - name: us-cent
       sourceConnectionRef: 
  	  name: "us-cent"
       destinationConnectionRef: 
  	  name: "us-east, us-west"
```

On the tenant level, we can add a `geoReplicationRef` field to quote the replica CR

```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTenant
metadata:
  name: geo-pulsar-tenant
  namespace: geo
spec:
  name: geo-tenant
  connectionRef:
    name: us-west
  adminRoles:
  - admin
  geoReplicationRef:
    name: pulsar-geo-sample
```

On the namespace level

```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarNamespace
metadata:
  name: geo-pulsar-namespace
  namespace: geo
spec:
  name: geo-pulsar-tenant/geo-ns
  connectionRef:
    name: us-west
  geoReplicationRef:
    name: pulsar-geo-sample
```

On the topic level

```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: geo-topic
  namespace: test
spec:
  name: persistent://geo-pulsar-tenant/geo-pulsar-namespace/geo-topic
  connectionRef:
    name: us-west
  geoReplicationRef:
    name: pulsar-geo-sample
```

**Comment by ahothan** [comment]
I have a few questions on the usage.

In the PulsarGeoReplication CR, what do the names "us-east" "us-west" "us-cent" correspond to in the source and destination ref fields? Are they pulsar cluster names? Where are the acceptable values defined?

My use case involves only 2 pulsar clusters (let's call them us-east and us-west) and let's assume I need to geo-replicate one topic and 1 subscription between the 2 clusters.
Could you describe how I should use this PulsarGeoReplication CR when I deploy pulsar us-east and pulsar west clusters on 2 different k8s clusters resp.?
Do I need to create (and apply) a different PulsarGeoReplication CR for each deployment?
Is there a way to geo-replicate a subscription for a geo-replicated topic?

Where do we enter the information required to connect to the peer pulsar cluster? (FQDN URL, JWT is configured,...)
Providing an example of CRs for the above use case would be great.

**Comment by ericsyh** [comment]
> I have a few questions on the usage.
> 
> In the PulsarGeoReplication CR, what do the names "us-east" "us-west" "us-cent" correspond to in the source and destination ref fields? Are they pulsar cluster names? Where are the acceptable values defined?
> 
> My use case involves only 2 pulsar clusters (let's call them us-east and us-west) and let's assume I need to geo-replicate one topic and 1 subscription between the 2 clusters. Could you describe how I should use this PulsarGeoReplication CR when I deploy pulsar us-east and pulsar west clusters on 2 different k8s clusters resp.? Do I need to create (and apply) a different PulsarGeoReplication CR for each deployment? Is there a way to geo-replicate a subscription for a geo-replicated topic?
> 
> Where do we enter the information required to connect to the peer pulsar cluster? (FQDN URL, JWT is configured,...) Providing an example of CRs for the above use case would be great.

The names of "us-east", "us-west" indicate the [PulsarConnection](https://github.com/streamnative/pulsar-resources-operator/blob/main/docs/pulsar_connection.md) which describes the connection info to a specific cluster. But I think we need to add broker address field on `PulsarConnection` because geo needs the broker address info.

**Comment by ericsyh** [comment]
For your case, I think the sample will look like:

```
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: us-east-pulsar-connection
  namespace: pulsar-resource
spec:
  adminServiceURL: http://<us-east-pulsar-domain>:8080
  # need to support this field
  brokerServiceURL: http://<us-east-pulsar-domain>:6650
  # optional
  authentication:
    token:
      secretRef:
        name: us-east-pulsar-sn-platform-vault-secret-env-injection
        key: brokerClientAuthenticationParameters
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: us-west-pulsar-connection
  namespace: pulsar-resource
spec:
  adminServiceURL: http://<us-west-pulsar-domain>:8080
  # need to support this field
  brokerServiceURL: http://<us-west-pulsar-domain>:6650
  # optional
  authentication:
    token:
      secretRef:
        name: us-west-pulsar-sn-platform-vault-secret-env-injection
        key: brokerClientAuthenticationParameters
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarGeoReplication
metadata:
  name: pulsar-geo-sample
  namespace: pulsar-resource
spec:
  replicationList:
    - name: us-west-geo-replica
      sourceConnectionRef: 
        name: "us-west"
      destinationConnectionRef: 
        name: "us-east"
    - name: us-east-geo-replica
      sourceConnectionRef: 
        name: "us-east"
      destinationConnectionRef: 
        name: "us-west"
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTenant
metadata:
  name: geo-pulsar-tenant
  namespace: pulsar-resource
spec:
  name: geo-tenant
  connectionRef:
    name: us-east-pulsar-connection
  adminRoles:
  - admin
  geoReplicationRef:
    name: pulsar-geo-sample
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTenant
metadata:
  name: geo-pulsar-tenant
  namespace: pulsar-resource
spec:
  name: geo-tenant
  connectionRef:
    name: us-west-pulsar-connection
  adminRoles:
  - admin
  geoReplicationRef:
    name: pulsar-geo-sample
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarNamespace
metadata:
  name: geo-pulsar-namespace
  namespace: geo
spec:
  name: geo-pulsar-tenant/geo-ns
  connectionRef:
    name: us-east
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarNamespace
metadata:
  name: geo-pulsar-namespace
  namespace: geo
spec:
  name: geo-pulsar-tenant/geo-ns
  connectionRef:
    name: us-west
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: geo-topic
  namespace: pulsar-resource
spec:
  name: persistent://geo-pulsar-tenant/geo-pulsar-namespace/geo-topic
  connectionRef:
    name: us-east
  geoReplicationRef:
    name: pulsar-geo-sample
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarTopic
metadata:
  name: geo-topic
  namespace: pulsar-resource
spec:
  name: persistent://geo-pulsar-tenant/geo-pulsar-namespace/geo-topic
  connectionRef:
    name: us-west
  geoReplicationRef:
    name: pulsar-geo-sample
```

**Comment by ahothan** [comment]
Keep in mind I have 2 pulsar clusters to deploy independently "us-west" pulsar cluster and "us-east" pulsar cluster on 2 different k8s clusters.
It seems to me that the set of CRs you describe needs to be split in 2 groups: one group that is applied on the us-west cluster and another that is deployed on the us-east cluster.
For example the last 2 CR will create a topic named persistent://geo-pulsar-tenant/geo-pulsar-namespace/geo-topic. The one with connectionRef set to "us-east" should be applied on the us-west cluster and vice versa?

For PulsarGeoReplication CR, shouldn't we also have 2 CRs, one applied on us-east and the other applied on us-west?

**Comment by ahothan** [comment]
The ideal solution could be that we deploy some kind of centralized resource operator that can control and coordinate the resources in multiple remote pulsar clusters (in my case 2), but then this becomes a remote controller, probably harder to implement.
I think in this case this pulsar resource operator has to be installed on the same k8s cluster as every pulsar cluster and can only control resources on the local pulsar cluster

**Comment by ericsyh** [comment]
> The ideal solution could be that we deploy some kind of centralized resource operator that can control and coordinate the resources in multiple remote pulsar clusters (in my case 2), but then this becomes a remote controller, probably harder to implement. I think in this case this pulsar resource operator has to be installed on the same k8s cluster as every pulsar cluster and can only control resources on the local pulsar cluster

Let me think about how to support under this scenario of only control resources on the local pulsar cluster. I think we need to create `us-east` and `us-west` `PulsarConnection` and `PulsarGeoReplication` for both deployment Kubernetes cluster. Let me try to figure out a sample for that.

**Comment by ericsyh** [comment]
We assume we have two k8s clusters and each running a resource operator, `us-east` pulsar cluster running under kube1 `us-esat-pulsar` ns and `us-west` pulsar cluster running under kube2 `us-west-pulsr` ns.

#### us-east cluster resource config

```
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: kube-1-us-east-pulsar-connection
  namespace: us-esat-pulsar
spec:
  adminServiceURL: http://<us-east-external-domain>:8080
  # need to support this field
  brokerServiceURL: http://<us-east-external-domain>:6650
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: kube-1-us-west-pulsar-connection
  namespace: us-esat-pulsar
spec:
  adminServiceURL: http://<us-west-external-domain>:8080
  # need to support this field
  brokerServiceURL: http://<us-west-external-domain>:6650
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarGeoReplication
metadata:
  name: kube-1-geo-config
  namespace: us-esat-pulsar
spec:
  replicationList:
    - name: us-east-geo-replica
      sourceConnectionRef: 
        name: "us-east"
      destinationConnectionRef: 
        name: "us-west"
```

#### us-west cluster resource config

```
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: kube-2-us-west-pulsar-connection
  namespace: us-west-pulsar
spec:
  adminServiceURL: http://<us-west-external-domain>:8080
  # need to support this field
  brokerServiceURL: http://<us-west-external-domain>:6650
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarConnection
metadata:
  name: kube-1-us-east-pulsar-connection
  namespace: us-west-pulsar
spec:
  adminServiceURL: http://<us-east-external-domain>:8080
  # need to support this field
  brokerServiceURL: http://<us-east-external-domain>:6650
---
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarGeoReplication
metadata:
  name: kube-2-geo-config
  namespace: us-west-pulsar
spec:
  replicationList:
    - name: us-west-geo-replica
      sourceConnectionRef: 
        name: "us-west"
      destinationConnectionRef: 
        name: "us-east"
```
