### ISSUE TITLE
feat[namespace+topic]: support schema related policies

### ISSUE THREAD

**Issue by ericsyh** [streamnative/pulsar-resources-operator#72]
```
apiVersion: resource.streamnative.io/v1alpha1
kind: PulsarNamespace
metadata:
  name: test-pulsar-namespace
  namespace: test
spec:
  name: test-tenant/testns
  connectionRef:
    name: test-pulsar-connection
  schemaCompatibilityStrategy
  isAllowAutoUpdateSchema
  schemaValidationEnforced
```
| Policy                      | Type   | Allowed values                                                                                                | API doc                                                                            |
|-----------------------------|--------|---------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|
| schemaCompatibilityStrategy | string | Full FullTransitive Forward ForwardTransitive Backward BackwardTransitive AlwaysCompatible AlwaysIncompatible | https://pulsar.apache.org/admin-rest-api/#operation/setSchemaCompatibilityStrategy |
| isAllowAutoUpdateSchema     | bool   | true, false                                                                                                   | https://pulsar.apache.org/admin-rest-api/#operation/setIsAllowAutoUpdateSchema     |
| schemaValidationEnforced    | bool   | true, false                                                                                                   | https://pulsar.apache.org/admin-rest-api/#operation/setSchemaValidationEnforced    |
